ids:
        source: "data/wikidata_paintings_ids_final_2.csv"
        columns:
                painting_id:
                        dtype: object
                        is_index: true
                        original_name: "item"
                        value_type: 'wikidata_url'
                author_id:
                        dtype: object
                        original_name: "author_wikidata"
                        value_type: 'wikidata_url'
                location_id:
                        dtype: object
                        original_name: "location_wikidata"
                        value_type: 'wikidata_url'

paintings:
        source: "data/wikidata_all_paintings.csv"
        columns:
                painting_id:
                        dtype: object
                        original_name: "item"
                        is_index: true
                        value_type: 'wikidata_url'

                creation_date:
                        dtype: datetime64[ns]
                        value_type: 'year'



authors:
        source: "data/wikidata_painters.csv"
        columns:
                author_id:
                        dtype: object
                        original_name: 'author_wikidata'
                        is_index: true
                        value_type: 'wikidata_url'
                painter:
                        dtype: object
                        original_name: 'author_name'
                author_country:
                        dtype: object
                        original_name: 'country_label'
                        
                date_of_birth:
                        dtype: datetime64[ns]
                        value_type: 'year'

                gender:
                        dtype: category
                        categories:
                                - male
                                - female
                                - NaN

locations:
        source: "data/wikidata_all_locations.csv"
        columns:
                location_id:
                        dtype: object
                        original_name: 'location_wikidata'
                        is_index: true
                        value_type: 'wikidata_url'
                location_name:
                        dtype: object
                        original_name: 'museum_name'
                location_country:
                        dtype: category
                        original_name: 'country_label'
                coordinates:
                        dtype: object
food_words:
        source: "data/paintings_with_food_nlp.csv"
        columns:
                painting_id:
                        dtype: object
                        original_name: 'item'
                        is_index: true
                        value_type: 'wikidata_url'
                image_path:
                        dtype: object
                        original_name: 'image_path'
                fruit:
                        dtype: int64
                bread:
                        dtype: int64
                cookware:
                        dtype: int64
                seafood:
                        dtype: int64
                wine:
                        dtype: int64
                meal:
                        dtype: int64
                cheese:
                        dtype: int64
                meat:
                        dtype: int64
                food:
                        dtype: int64
                beverage:
                        dtype: int64
                dairy:
                        dtype: int64
                vegetable:
                        dtype: int64
                dessert:
                        dtype: int64

food_found:
        source: "data/paintings_with_food_cv.csv"
        columns:
                painting_id:
                        dtype: object
                        original_name: 'item'
                        is_index: true
                        value_type: 'wikidata_url'
                predictions:
                        dtype: object
                
